fix: update GitHub workflow to new solution format

diff --git a/.github/workflows/format.yml b/.github/workflows/format.yml
--- a/.github/workflows/format.yml
+++ b/.github/workflows/format.yml
@@ -30,7 +30,7 @@ jobs:
                 dotnet-version: ${{ matrix.dotnet-version }}
 
             - name: ⚙️ Restore Dependencies
-              run: dotnet restore ./Yukihana.sln
+              run: dotnet restore ./Yukihana.slnx
 
             - name: 🔍 Check Formatting
-              run: dotnet format ./Yukihana.sln --exclude dotnet --verify-no-changes --severity error || { echo "::error file=Code Formatting::Some files need formatting. Run 'dotnet format' locally."; exit 1; }
+              run: dotnet format ./Yukihana.slnx --exclude dotnet --verify-no-changes --severity error || { echo "::error file=Code Formatting::Some files need formatting. Run 'dotnet format' locally."; exit 1; }
